### ISSUE TITLE
errors while importing .x

### ISSUE THREAD

**Issue by itsOhNoAaDi** [oguna/Blender-XFileImporter#1]
i installed this addon but when ever i import .x direct x file it shows some paython errors
![Blender Info Log 27-11-2022 10_49_22](https://user-images.githubusercontent.com/119150136/204120891-3da321e4-300f-4b99-976b-f9691e84d2e3.png)
![Blender 27-11-2022 10_41_05](https://user-images.githubusercontent.com/119150136/204120893-81d55544-7d3d-4940-89e3-2cc50d7c7a7c.png)

**Comment by oguna** [comment]
Thnk you for your report.
I have reproduced this error messages in Blender 3.3 LTS.
This issue may be due to changing specifications.
I'll solve this issue.

**Comment by oguna** [comment]
This change of specifications was occurred at ver 3.2

https://developer.blender.org/rB891268aa824f0f
